services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://db:5432/ktor_server_db"
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - backend

  db:
    image: postgres:16.6
    volumes:
      - ktor_web_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ktor_server_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d ktor_server_db" ]
      interval: 1s

volumes:
  ktor_web_data:
